name: Deploy BindKit site

on:
  push:
    branches: [ main ]
    paths:
      - 'site/**'
      - 'VERSION'
      - '.github/workflows/deploy-site.yml'
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show version
        id: version
        shell: bash
        run: |
          if [[ -f VERSION ]]; then
            V=$(cat VERSION | tr -d '\r\n')
          else
            V=${GITHUB_REF_NAME:-dev}
          fi
          echo "version=$V" >> $GITHUB_OUTPUT
          echo "Detected version: $V"

      - name: Prepare static build with version
        shell: bash
        run: |
          mkdir -p build
          cp -r site/* build/
          if [[ -f build/index.html ]]; then
            sed -i "s/__BINDKIT_VERSION__/${{ steps.version.outputs.version }}/g" build/index.html
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: build

