name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semantic version bump (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements.txt') { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Bump version
        id: bump
        shell: pwsh
        run: |
          $path = "VERSION"
          if (!(Test-Path $path)) { '0.1.0' | Out-File -NoNewline $path }
          $version = (Get-Content $path -Raw).Trim()
          if ($version -notmatch '^[0-9]+\.[0-9]+\.[0-9]+$') { Write-Error "Invalid VERSION file: $version" }
          $parts = $version.Split('.')
          $major=[int]$parts[0]; $minor=[int]$parts[1]; $patch=[int]$parts[2]
          switch ('${{ github.event.inputs.release_type }}') {
            'major' { $major++; $minor=0; $patch=0 }
            'minor' { $minor++; $patch=0 }
            default { $patch++ }
          }
          $newVersion = "$major.$minor.$patch"
          Set-Content -NoNewline -Path $path -Value $newVersion
          echo "VERSION=$newVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "new_version=$newVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Commit version bump and tag
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "chore(release): v${{ env.VERSION }}" || echo "No changes to commit"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin HEAD:${{ github.ref_name }}
          git push origin "v${{ env.VERSION }}"

      - name: Build executable with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --name DesktopUtilityGUI --windowed main.py

      - name: Install Inno Setup
        shell: pwsh
        run: |
          choco install innosetup --no-progress -y

      - name: Build installer with Inno Setup
        shell: pwsh
        run: |
          $iscc = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
          & $iscc "installer\desktop_utility_gui.iss" /DMyAppVersion=${{ env.VERSION }}

      - name: Create GitHub Release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: |
            installer/output/DesktopUtilityGUI-${{ env.VERSION }}-Setup.exe
          draft: false
          prerelease: false

